### ISSUE TITLE
Entry management

### ISSUE THREAD

**Issue by BelleCDXX** [DasLab/Server_RMDB#35]
- contact Sanbonmatsu lab and others to deposit their data  [rhiju]
- Featured Contributor: Julius Lucks [and set up for: Karissa, Alain, molecules, etc.]
- update RMDB to include data from (sripakdeevong, 2011) paper. [rhiju]

**Comment by rhiju** [comment]
these are personal things for rhiju -- other issues in th elist were moved to separate issues.
