### ISSUE TITLE
Side bar in detail page

### ISSUE THREAD

**Issue by BelleCDXX** [DasLab/Server_RMDB#44]
When user clicks on side-bar and sees ‘general’, please put at top right of that side-bar an icon like this one: 
![image](https://user-images.githubusercontent.com/15862212/34028909-87412ff0-e11a-11e7-90c4-eaba7719f9f4.png)

and have it link to 
https://rmdb.stanford.edu/deposit/specs/#construct

If user clicks on ‘annotations’, 

have the logo link to
https://rmdb.stanford.edu/deposit/specs/#annotation

(Later in 2017 or early 2018 I will be updating the https://rmdb.stanford.edu/deposit/specs page based on user input, but I think this will make my life easier.)

**Comment by rhiju** [comment]
done!
