### ISSUE TITLE
Move MAINTENANCE.md to issues

### ISSUE THREAD

**Issue by BelleCDXX** [DasLab/Server_RMDB#46]
There is a file

https://github.com/DasLab/Server_RMDB/blob/master/MAINTENANCE.md

Again move these to Issues. And mark as closed everything that verify is done. Then remove MAINTENANCE.md from the repo.

**Comment by rhiju** [comment]
actually @BelleCDXX pointed out that these are not issues, they are instructions for people doing maintenance. I moved that stuff to README.md
