### ISSUE TITLE
Remove licensing of ribokit stuff out of RMDB

### ISSUE THREAD

**Issue by rhiju** [DasLab/Server_RMDB#61]
- need to move ribokit/primerize/mapseeker licensing over to (new) ribokit-license server and database instead of hosted at RMDB.

**Comment by rhiju** [comment]
License server is setup.

Let's change the 'tools' menu on RMDB to point to
http://ribokit-license.stanford.edu/download

**Comment by rhiju** [comment]
Please also resolve these very small issues:
https://github.com/DasLab/Server_Ribokit_License/issues

**Comment by BelleCDXX** [comment]
done!
