### ISSUE TITLE
Allow search of Pubmed ID

### ISSUE THREAD

**Issue by rhiju** [DasLab/Server_RMDB#64]
When we set up a Pubmed ID (PMID) for an entry, it would be nice to be able to type in that number into 'search' and then get all entries with that PMID. Is that easy to do? I guess we need to update the search index when someone updates PMID.

**Comment by rhiju** [comment]
See also #78 which asks for links to PMID text on each RDAT page to lead to the same search.

**Comment by tkaragianes** [comment]
Closed by #115.

![Screenshot 2024-07-23 at 14-12-09 RMDB RNA Mapping DataBase](https://github.com/user-attachments/assets/9ad835e8-0df7-49b8-8eec-9e671e539020)
