### ISSUE TITLE
Enable search by Pubmed ID

### ISSUE THREAD

**Issue by rhiju** [DasLab/Server_RMDB#78]
Example: we should be able to click on the "PMID: 26035425" text in [this page](https://rmdb.stanford.edu/detail/GLYCFN_KNK_0003) and see _all_ RMDB entries related to that Pubmed ID.

**Comment by rhiju** [comment]
Also, if I type part of a paper title or author or Pubmed ID in the search box, i should get entries. See also #79 .

**Comment by tkaragianes** [comment]
Closed by #115.

![Screenshot 2024-07-23 at 14-12-09 RMDB RNA Mapping DataBase](https://github.com/user-attachments/assets/1afc05db-a0f1-49aa-be6c-337895478f35)
