### ISSUE TITLE
Enable search by author

### ISSUE THREAD

**Issue by rhiju** [DasLab/Server_RMDB#79]
If I search by "Kappel" in the search box, I get nothing, even though many entries are related to papers by Kappel.

**Comment by tkaragianes** [comment]
Closed by #115. 

![Screenshot 2024-07-23 at 14-10-29 RMDB RNA Mapping DataBase](https://github.com/user-attachments/assets/68418a60-40e4-4a81-80f4-8f4e1dd9fc91)
